# Site
repository: Kyuuu827/Kyuuu827.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lee Chankyu
title: Backend Developer
email: lck0827@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Kyuuu827
# facebook_username: lck0827
#instagram_username: Kyuuu827
linkedin_username: chankyu-lee-07282917a
#youtube_username: lck0827

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-blog
  url: Kyuuu827.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 백엔드 개발자 이찬규 입니다.<br/><br/>
  현재 웹 서비스와 백오피스 개발 업무를 메인으로 진행하며 개인의 성과가 회사의 성장, 구성원들의 업무 효율 증대에 기여하는 것을 피부로 느끼고 있습니다. 
  개발자로서 개발 업무에만 집중하는 것을 넘어, 사업의 방향성과 도메인에 대한 깊은 이해를 바탕으로 최대 성과를 낼 수 있는 방안에 대한 의견을 제시하고 기여할 수 있도록 집중합니다. <br/><br/> 
  소규모의 신규 백오피스는 직접 기획/개발/배포/운영을 진행해보며 사고의 스펙트럼을 넓히는 경험을 하였습니다. 더불어 동료들의 적극적인 피드백을 
  받으며 부족한 점을 보완하는 것에 큰 보람과 즐거움을 느낍니다. 로그의 힘을 믿고 이슈가 발생하지 않아도 모니터링을 통해 문제점을 발견하여 먼저 개선하고 의견을 요청합니다.<br/><br/>
  새로운 기술 지식의 습득, 도입에 적극적이고 이는 큰 즐거움입니다. 단순히 새로운 기술을 익혔다는 사실 자체에 큰 의미를 두진 않습니다. 
  배움의 과정에서 발견하게 되는 내 지식의 빈틈을 채우는 것과 개발의 사고를 넓히는 것을 중요하게 생각합니다. 
  이와 같이 반복적인 배움의 시도를 통해 얻게되는 지식의 핵심들을 잘 조합하여, 담당하는 서비스의 성능 향상을 이뤄내고 이를 통해 유저들이 서비스를 안정적으로 
  이용할 수 있게 만들고자 합니다.<br/><br/>
  **"급박한 상황에도 흔들리지 않는 맷집 그리고 평정심"**<br/><br/>
  저를 잘 표현하는 문장입니다. 어떤 어려움을 직면해도 반드시 해결할 수 있다는 확신이 있고 그런 상황에서도 평정심을 잘 유지할 수 있습니다. 이러한 평정심은 
  좀 더 신속하게 효율적인 해결책을 찾아낼 수 있도록 도움을 주는 것 같습니다.

#  I am most skilled in: <mark>Python</mark> and <mark>Go</mark>

content:
  - title: Skill
    layout: list # Type of _data section (list/text)
    content:
      - layout: left
        title: Backend
        description: |
          * **Python, Django(DRF), Flask**
            - Django 프레임워크에 익숙하며, 원하는 기능의 API 개발이 가능합니다.
            - Python 프레임워크, 라이브러리를 탐구하고 적용하는 것에 흥미가 있습니다.<br/><br/>
          * **Go, Gin, gRPC, GORM, Protocol Buffers(protobuf)**
            - Gin 웹 프레임워크를 사용하여 백오피스를 개발한 경험이 있습니다.
            - gRPC를 이해하고 protobuf 방식을 통한 API 개발이 가능합니다.
            - SQL raw query 외에 GORM을 사용한 API 개발 경험이 있습니다.
            - 해당 기술들을 활용하여 신규 백오피스 서비스의 기획/개발/배포/운영을
              진행하였습니다.<br/><br/>
          * **Java, Kotlin, Spring Boot, JPA, Hibernate, Querydsl, Mybatis**
            - 기존에 개발되어 운영되고 있는 백오피스를 Kotlin + Spring Boot 기술스택으로 마이그레이션을 진행하며 기술을 습득 중입니다.
            - 프로젝트 생성부터 직접 진행해보며 프로젝트의 구조 및 클린 아키텍처에 대한 좀 더 고민하고, 프레임워크의 동작원리를 이해하려고 노력합니다.
      - layout: left
        title: DevOps
        description: |
          * AWS가 제공하는 서비스들을 사용한 경험이 있고 현업에서 자주 사용하며 최적의 아키텍처 구성에 대해 고민합니다. 
          * MySQL, MongoDB, AWS Aurora, DocumentDB, DynamoDB
          * AWS SQS, Lambda, S3, Cloud Watch, EC2, Elasticache, Kinesis
      - layout: left
        title: Frontend
        description: |
          * **Vue.js (version 2.0 & 3.0)**
            - Version 2.0 과 3.0을 모두 사용하여 개발을 진행한 경험이 있습니다.
            - Ant Design Vue와 같은 라이브러리를 사용한 백오피스 개발이 가능합니다.

  - title: Experience # Title for the section
    layout: list # Type of _data section (list/text)
    content:
      - layout: left
        title: 중고나라(Joonggonara)
        link: https://web.joongna.com
        # link_text: boringcompany.com
        sub_title: 아키텍처팀, Backend Developer
        caption: 2022.03 - Present
        quote: >
          카페 회원 누적 1900만, 모바일 앱 누적 1000만 다운로드 달성의 중고거래 온라인 플랫폼
        description: | # this will include new lines to allow paragraphs
          * 백오피스 개발 - [회사 블로그 관련 게시글](https://blog.joongna.com/%EC%A4%91%EA%B3%A0%EB%82%98%EB%9D%BC-%EB%B0%B1%EC%98%A4%ED%94%BC%EC%8A%A4-%EA%B0%9C%EB%A1%A0-feat-%EA%B8%B0%EC%88%A0-%EC%8A%A4%ED%83%9D-6e29763cae9d)
          * 통합 모니터링 시스템 개발 및 유지 보수
          * 카페 게시글 크롤링 및 필터링 및 유지 보수
          * 셀러 전용 서비스/어드민 개발
          * 사내 배포 시스템 개발
          * 사내 계정 생성/삭제 자동화 개발
      - title: GC녹십자
        link: https://www.gccorp.com
        sub_title: Medical Affair (Clinical Trial)
        caption: 2019.07 - 2021.09
        quote: >
          연 매출 1조 7천억원 이상의 국내 굴지의 제약사
        description: |
          * 시판 후 조사(PMS) Study Manager
            - 인슐린 주사제, 수두 백신 등의 PMS 과제 Management
          * 연구자 주도 임상 연구(IIT) Study Manager
            - EGFR 표적항암제, 항암보조제(뉴라펙) 관련 임상 연구 Management
          * 관찰연구(Observational Study) Study Manager
            - 항암보조제(뉴라펙) 관찰연구 초기 세팅

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: 백오피스 API Migration (Go(gRPC) -> Spring Boot(Rest API))
          #        link: github.com/Kyuuu827
          #        link_text: Project Website
          #        additional_links:
          #          - title:  Kyuuu827
          #            icon: fab fa-github
        #            url: github.com/Kyuuu827
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          <b>Skill: Kotlin 1.7.22, Spring Boot 3.0.6, Spring Data JPA, Hibernate, Querydsl, AuroraDB</b>
        description: | # this will include new lines to allow paragraphs
          * Kotlin + Spring Boot로의 서버 기술스택 전환 진행중(2023.5월 기준)
      - layout: top-middle
        title: 회원등급, 카테고리별 게시글 자동 삭제 기능 개발
        quote: >
          <b>Skill: Python, Flask, AWS Lambda, Amazon Elasticache, Amazon Kinesis, AuroraDB, Vue,js</b>
        description: | # this will include new lines to allow paragraphs
          * 사내 정책에 따른 회원등급, 카테고리별 게시글 작성 횟수 제한 초과시 게시글 자동 삭제 기능 개발
          * 안전결제 여부, 판매/매입 여부 등과 같은 게시글 특징에 따라 각각 다른 조건 적용
          * 정책 적용 받지 않는 예외 계정 관리 페이지 개발
          * 계정별 게시글 집계(시간, 일 기준) 및 카테고리별 기준의 Elasticache 캐싱을 통한 기능 구현
          * 게시글 필터링 및 삭제 API 호출 로직은 AWS Lambda를 통해 구현<br/><br/>
      - layout: top-middle
        title: 사내 계정 관리 자동화 기능 개발
        quote: >
          <b>Skill: Go, Gin, GORM, AWS-SDK, AuroraDB, Vue,js</b>
        description: | # this will include new lines to allow paragraphs
          * 신규입사/퇴사 또는 기존 직원의 권한 변경에 요청에 따른 각종 계정 관리 자동화를 위한 개발
          * 계정 신규 생성, 계정 삭제, 비밀번호 초기화 기능 개발
          * 계정 생성 요청 화면 개발
          * Bitbucket 워크스페이스 초대 기능: Bitbucket Rest APIs 2.0을 통한 구현
          * AWS IAM 계정 생성/삭제 기능: aws-sdk-go 라이브러리 사용
          * IPA 계정 생성/수정/삭제 기능: freeIPA 라이브러리 커스텀을 통한 기능 구현
          * 계정 생성 요청시 Slack 메시지 발송을 통한 관리자의 계정 생성 승인/반려 결정 및 결과 안내 기능 개발
      - layout: top-middle
        title: 사내 HR 프로그램 진행을 위한 전 직원 조 편성 백오피스 개발
        quote: >
          <b>Skill: Python, AWS Chalice, AWS Lambda, API Gateway, AuroraDB, Vue.js</b>
        description: | # this will include new lines to allow paragraphs
          * 격주로 진행되는 사내 HR 프로그램 진행을 위한 직원 리스트 관리, 조 편성 및 결과 통보를 위한 백오피스 개발
          * 입사자/퇴사자 발생시 전체 리스트 수정 기능, 행사 진행시 불참자 반영 및 랜덤 조편성 알고리즘 추가
          * 전 직원이 쉽게 조회/검색 가능한 웹 페이지 개발
          * AWS Chalice 프레임워크 신규 적용을 통한 AWS Lambda, API Gateway 연동 및 배포<br/><br/>
      - layout: top-middle
        title: 이미지 Webp 변환 및 S3 업로드 기능 개발 - Google SEO 이미지 최적화
        quote: >
          <b>Skill: Python, Serverless Framework, AWS Lambda, SQS, S3, PIL</b>
        description: | # this will include new lines to allow paragraphs
          * Google SEO 이미지 최적화를 위한 원본 이미지의 Webp 변환 및 S3 업로드 Api 개발
          * Serverless Framework를 통한 AWS Lambda handling
          * AWS SQS 메시지 큐 방식을 통한 이미지 전송 및 Lambda Trigger
          * 이미지 변환 라이브러리(PIL) 사용 (기존 포맷 -> Webp)
          * 이미지 상태에 따라 발생할 수 있는 다양한 에러(encoding 에러, 비정상적 이미지 에러, Webp 규격 초과 에러 등) handling
          * 지속적인 모니터링을 통한 logging 보완<br/><br/>
      - layout: top-middle
        title: 사내 배포 시스템 개발
        quote: >
          <b>Skill: Go, GORM, gRPC, Protobuf, AuroraDB, Bitbucket-Pipeline, Vue.js</b>
        description: | # this will include new lines to allow paragraphs
          * 사내 개발자들의 배포 진행 및 배포 히스토리 관리를 위한 “배포 시스템” 개발 프로젝트의 기획 / 개발 / 운영 단독 진행
          * 팀별/개인별 배포 예정일, 배포 내용, Jira 이슈 넘버 등의 정보 등록/조회/수정/조건부 삭제 기능 구현(CRUD)
          * Bitbucket REST API, Jira REST API, JQL을 활용하여, 배포 과정에서 필요한 Bitbucket 및 Jira 이슈 handling 기능 구현
          * 버튼 원클릭 배포 기능 및 배포 결과에 따른 화면 기능 구현(배포 중지/실패 시 재배포 가능)
          * 현재 전 개발 부서가 배포 일정 등록, 배포 진행, 배포 히스토리 관리를 위해 이용 중<br/><br/>
      - layout: top-middle
        title: 셀러 전용 플랫폼 서비스 및 관리자 백오피스 개발
        quote: >
          <b>Skill: Python, Django Rest Framework, S3, AuroraDB, Vue.js</b>
        description: | # this will include new lines to allow paragraphs
          * 사업팀의 효율적인 셀러 관리를 위한 총체적인 관리 기능 신규 개발
          * 계약 내역, 관련 문서 S3 업로드 및 다운로드, 히스토리 조회 등의 기능 구현
          * 셀러 상태/계약 히스토리에 따른 계약 종료/연장/재계약 등의 기능 구현
          * 사업 부서의 셀러 계약 관리 업무 방식 전환(엑셀 → 백오피스)<br/><br/>
      - layout: top-middle
        title: 사기 의심 채팅 모니터링 기능 고도화
        quote: >
          <b>Skill: Python, Flask, SQLAlchemy, AuroraDB, MongoDB, Vue.js</b>
        description: | # this will include new lines to allow paragraphs
          * 모니터링 요원들의 사기의심채팅 모니터링 목적의 채팅 화면 개발을 통한 모니터링 업무 효율 개선
          * 사기의심 여부 반복 체크를 위한 프로세스 개발 및 도입
          * 사기의심 유저와의 동일 디바이스 uuid 검출 여부 조회 기능 개발
          * 사기 의심 채팅 적발에 따른 즉각적인 회원 제재 및 반복 검토를 통한 적중률 증가에 기여<br/><br/>

  - title: Education # Title for the section
    layout: list # Type of _data section (list/text)
    content:
      - layout: left
        title: 경희대학교 (Kyunghee University)
        caption: 2009.03 - 2015.02
        sub_title: Bachelor of Science, Medical Science
        description: | # this will include new lines to allow paragraphs
          * 생명과학, 화학 관련 주요 전공 과목 이수
          * 해부학, 약리학 등의 기초의학 관련 주요 전공 과목 이수
          * 유전자 재조합, 형질전환 등과 같은 다양한 주제의 in vivo, in vitro 실험교육을 통한 연구능력 배양 훈련

  - title: Description of me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - **"Growth itself contains the germ of happiness"**<br>
      제가 인생의 좌표로 삼고 있는 명언입니다. 이와 같이 인생의 가장 중요한 가치는 '**성장**'이라고
      생각합니다. 회사와 개인의 지속적인 동반성장을 도모하는 개발자가 되고자 합니다.<br/><br/>
      - 함께 "성장" 할 때 몇 배의 보람과 행복을 느낍니다. 이전 직군에서 Study Manager 역할을 수행하며, **함께 목표를 달성할 때의 희열**을 여러 번 
      느꼈고, 현재는 백엔드 개발자로 근무하며 팀원들과 함께 보람과 희열을 느끼며 매일매일 즐겁게 성장하고 있습니다.

#      Look at this cool image
#      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
