# Site
repository: Kyuuu827/Kyuuu827.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lee Chankyu
title: Backend Developer
email: lck0827@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  Kyuuu827
# facebook_username: lck0827
#instagram_username: Kyuuu827
linkedin_username: chankyu-lee-07282917a
#youtube_username: lck0827

# Additional icon links
additional_links:
- title: blog
  icon: fas fa-blog
  url: Kyuuu827.tistory.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요. 백엔드 개발자 이찬규 입니다.<br/><br/>
  웹 서비스와 연관된 여러 내부 모듈과 백오피스 개발 업무를 메인으로 진행해오며 개인의 성과가 회사의 성장, 구성원들의 업무 효율 증대에 기여하는 것을 피부로 느끼고 있습니다. 
  현재는 메인 상품서비스를 담당하여 좀 더 다양한 서비스 개발을 경험하며 퀄리티  있는 성장을 위해 고군분투하고 있습니다. 개발자로서 개발 업무에만 집중하는 것을 넘어,
  서비스의 방향성과 도메인에 대해 깊이 이해하려고 노력하며 최대 성과를 낼 수 있는 방안에 대한 의견을 제시하고 기여할 수 있는 개발자가 되는 것에 집중합니다. <br/><br/> 
  서비스의 기획/개발/배포/운영을 모두 직접 진행해보며 서비스가 공급되기까지의 일련의 과정을 모두 경험하였습니다. 이러한 과정에서 동료들의 적극적인 피드백을 
  받으며 부족한 점을 보완하는 것에 큰 보람과 즐거움을 느낍니다. 이를 통해 부족한 점을 보완하고 서비스 개선 방안으로 즉각 반영하는 것을 추구합니다.<br/><br/>
  새로운 기술 지식의 습득, 도입에 적극적이고 이는 큰 즐거움입니다. 단순히 새로운 기술을 익혔다는 사실 자체에 큰 의미를 두진 않습니다. 
  배움의 과정에서 발견하게 되는 내 지식의 빈틈을 채우는 것과 개발의 사고를 넓히는 것을 중요하게 생각합니다. 
  이와 같이 반복적인 배움의 시도를 통해 얻게되는 지식의 핵심들을 잘 조합하여, 담당하는 서비스의 성능 향상을 이뤄내고 이를 통해 유저들이 서비스를 안정적으로 
  이용할 수 있게 만들고자 합니다.<br/><br/>
  **"급박한 상황에도 흔들리지 않는 맷집 그리고 평정심"**<br/><br/>
  저를 잘 표현하는 문장입니다. 어떤 어려움을 직면해도 반드시 해결할 수 있다는 확신이 있고 그런 상황에서도 평정심을 잘 유지할 수 있습니다. 이러한 평정심은 
  좀 더 신속하게 효율적인 해결책을 찾아낼 수 있도록 도움을 주는 것 같습니다.

#  I am most skilled in: <mark>Python</mark> and <mark>Go</mark>

content:
  - title: Skill
    layout: list # Type of _data section (list/text)
    content:
      - layout: left
        title: Backend
        description: |
          * **Python, Flask, Django(DRF), SQLAlchemy**
            - Flask-RESTX를 활용한 REST API 개발에 능숙합니다.
            - Django 프레임워크에 익숙하며, 원하는 기능의 API 개발이 가능합니다. 
            - Python 프레임워크, 라이브러리를 탐구하고 적용하는 것에 흥미가 있습니다.<br/><br/>
          * **Go, Gin, gRPC, GORM, Protocol Buffers(protobuf)**
            - Gin 웹 프레임워크를 사용하여 백오피스를 개발한 경험이 있습니다.
            - gRPC를 이해하고 protobuf 방식을 통한 API 개발이 가능합니다.
            - SQL raw query 외에 GORM을 사용한 API 개발 경험이 있습니다.
            - 해당 기술들을 활용하여 신규 백오피스 서비스의 기획/개발/배포/운영을
              진행하였습니다.<br/><br/>
          * **Java, Kotlin, Spring Boot, JPA, Hibernate, Querydsl, Mybatis**
            - Java + Spring framework 기반의 상품서비스 개발 및 유지 보수를 담당하게 되어 기술 습득에 집중하고 있습니다. 
            - 기존에 개발되어 운영되고 있는 백오피스를 Kotlin + Spring Boot 기술스택으로 마이그레이션을 진행하며 기술을 습득 중입니다.
            - 프로젝트 생성부터 직접 진행해보며 프로젝트의 구조 및 클린 아키텍처에 대한 좀 더 고민하고, 프레임워크의 동작원리를 이해하려고 노력합니다.
      - layout: left
        title: DevOps
        description: |
          * AWS가 제공하는 서비스들을 사용한 경험이 있고 현업에서 자주 사용하며 최적의 아키텍처 설계에 대해 고민합니다. 
          * MySQL, MongoDB, AWS Aurora, DocumentDB
          * AWS SQS, Lambda, S3, Cloud Watch, EC2, Elasticache, Kinesis
      - layout: left
        title: Frontend
        description: |
          * **Vue.js (version 2.0 & 3.0)**
            - Version 2.0 과 3.0을 모두 사용하여 개발을 진행한 경험이 있습니다.
            - Ant Design Vue와 같은 라이브러리를 사용한 백오피스 개발이 가능합니다.

  - title: Experience # Title for the section
    layout: list # Type of _data section (list/text)
    content:
      - layout: left
        title: 중고나라(Joonggonara)
        link: https://web.joongna.com
        # link_text: boringcompany.com
        sub_title: 아키텍처팀, Backend Developer
        caption: 2022.03 - Present
        quote: >
          카페 회원 누적 1900만, 모바일 앱 누적 1000만 다운로드 달성의 중고거래 온라인 플랫폼
        description: | # this will include new lines to allow paragraphs
          * 상품서비스 개발 및 유지 보수
            - Skill Keywords: Java, Spring Boot, Gradle, Mybatis, Go, AWS Lambda, SQS, Amazon Aurora, ElastiCache
          * 통합 모니터링 시스템 개발 및 유지 보수
            - Skill Keywords: Python, Flask, Amazon Aurora, OpenSearch, ElastiCache, Vue.js
          * 카페 게시글 크롤링 및 필터링 모듈 개발 및 유지 보수
            - Skill Keywords: Python, AWS Lambda, SQS, ElastiCache, Kinesis
          * 셀러 전용 서비스/어드민 개발
            - Skill Keywords: Python, Django, Amazon Aurora, DynamoDB, ElastiCache, Vue.js
          * 사내 배포 시스템 개발
            - Skill Keywords: Go, gRPC, GORM, Protobuf, Amazon Aurora, Bitbucket-Pipeline, Vue.js
          * 사내 계정 관리 시스템 자동화 개발
            - Skill Keywords: Go, Gin, GORM, AWS-SDK, Amazon Aurora, Vue.js
      - title: GC녹십자
        link: https://www.gccorp.com
        sub_title: Medical Affair (Clinical Trial)
        caption: 2019.07 - 2021.09
        quote: >
          연 매출 1조 7천억원 이상의 국내 굴지의 제약사
        description: |
          * 시판 후 조사(PMS) Study Manager
            - 인슐린 주사제, 수두 백신 등의 PMS 과제 Management
          * 연구자 주도 임상 연구(IIT) Study Manager
            - EGFR 표적항암제, 항암보조제(뉴라펙) 관련 임상 연구 Management
          * 관찰연구(Observational Study) Study Manager
            - 항암보조제(뉴라펙) 관찰연구 초기 세팅

  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: 상품 시스템 개발 및 유지/보수
          #        link: github.com/Kyuuu827
          #        link_text: Project Website
          #        additional_links:
          #          - title:  Kyuuu827
          #            icon: fab fa-github
          #            url: github.com/Kyuuu827
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          <b>Skill: Java, Spring Boot, Gradle, Mybatis, Go, AWS Lambda, SQS, Amazon Aurora, ElastiCache</b>
        description: |
          * 카페 - 앱 상품 등록 연동 프로세스 고도화
          * 상품 상세 조회시 레디스 조회 매서드 클래스 분리 - 불필요 프록시 인터셉터 제거<br/><br/>
      - layout: top-middle
        title: 앱 회원 신고 관리 개발
        quote: >
          <b>Skill: Python, Flask, AuroraDB, Vue.js</b>
        description: |
          * 기존 Java 8 + Spring Framework로 개발되어 있던 백오피스의 "신고 관리" 기능을 Python + Flask 기술스택으로 개발된 백오피스로 마이그레이션
          * 변경된 기능에 최적화 된 RDB Schema 변경 적용 및 데이터 마이그레이션
          * "신고 관리" 기능만 Python 기반의 플랫폼으로 이관함에 따라 이와 연동되어 있는 Java 기반의 프로젝트 코드 수정 및 개선
          * SQL Query 튜닝을 통한 기능 향상
          * 앱 PUSH 발송시, 신고 정책에 따른 템플릿 제공 기능 추가
          * 분리되어있던 앱 신고 처리 관련 기능들의 통합
          * 관리자 신고 처리, 앱 PUSH, 앱 상품 자동 숨김 처리, 통계 엑셀 다운로드
          * 운영, CS 및 비지니스 부서들의 업무 효율 상승<br/><br/>
      - layout: top-middle
        title: 카페, 앱 회원 양방향 제재 연동 개발
        quote: >
          <b>Skill: Python, Flask, AuroraDB, Amazon Opensearch, Vue.js</b>
        description: |
          * 카페, 앱 연동 회원의 동시 회원 제재 자동화 기능 개발
          * 현재 사용중인 회원 제재 관련 API들의 결합에 따른 기능, 사용자 편의성 저하를 방지하고 데이터 정합성을 보장하는 것이 개발의 Key Point
          * 양방향 제재 진행 프로세스 트랜잭션 처리
          * FDS 관련 정책에 따른 제재시 FDS 등록 프로세스 개발
          * 카페 게시글 자동 삭제 및 상품 API와의 연동을 통한 앱 상품 노출 상태 변경 기능 개발
          * 오처리, 기타 사유 등으로 인한 제재 처리 취소시 양방향 연동 취소 및 카페 게시글, 앱 상품 노출 상태 복원 기능 개발<br/><br/>
      - layout: top-middle
        title: 백오피스 API Migration (Go(gRPC) -> Spring Boot(Rest API))
        quote: >
          <b>Skill: Kotlin 1.7.22, Spring Boot 3.0.6, Spring Data JPA, Hibernate, Querydsl, AuroraDB</b>
        description: |
          * Go + gRPC로 개발되어 있는 사내 서비스를 Kotlin + Spring Boot로의 서버 기술스택 전환 진행중
          * 프로젝트 생성, Gradle 빌드설정, Hikari connection pool 등 초기 세팅 직접 진행
          * Spring Data JPA, QueryDSL를 사용하여 직관적인 SQL 쿼리 관리
          * 배포 진행 state 값 확인시 interval 호출 방식에서 Web Socket 통신을 통한 체크 방식으로의 전환 계획 -> 실시간에 가까운 state 업데이트 및 데이터 정합성 보장 목적<br/><br/>
      - layout: top-middle
        title: 회원등급, 카테고리별 게시글 자동 삭제 기능 개발
        quote: >
          <b>Skill: Python, Flask, AWS Lambda, Amazon Elasticache, Amazon Kinesis, AuroraDB, Vue,js</b>
        description: |
          * 사내 정책에 따른 회원등급, 카테고리별 게시글 작성 횟수 제한 초과시 게시글 자동 삭제 기능 개발
          * 카테고리, 안전결제 여부, 판매/매입 여부 등의 조건에 따라 다른 기준이 적용되므로 이를 구분하여 게시글을 집계하고 정책을 적용하는 것이 Key Point.
          * RDB Schema 모델링, AWS Kinesis 트리거 및 Event Handler 개발
          * Redis Zset 자료구조 및 관련 기능들을 사용하여 게시글 집계에 사용
          * 정책 적용 받지 않는 예외 계정 관리 API 개발
          * 모니터링의 요원들의 업무 효율 개선 및 관련 CS 업무량 감소 효과<br/><br/>
      - layout: top-middle
        title: 사내 계정 관리 자동화 기능 개발
        quote: >
          <b>Skill: Go, Gin, GORM, AWS-SDK, AuroraDB, Vue,js</b>
        description: |
          * 신규입사/퇴사 또는 기존 직원의 권한 변경에 요청에 따른 각종 계정 관리 자동화를 위한 개발
          * RDB Schema 모델링, 계정 신규 생성, 계정 삭제, 비밀번호 초기화 기능의 RESTful API 개발
          * Bitbucket 워크스페이스 초대 기능 -> Bitbucket Rest APIs 2.0을 통한 구현
          * AWS IAM 계정 생성/삭제 기능 -> aws-sdk-go 라이브러리 적용
          * IAM 계정의 온전한 생성/삭제를 위해서는 AWS IAM 계정의 필수 요건에 대한 정확한 이해를 바탕으로 적절한 엔드포인트를 선택해야함.
          * IAM 유저, 로그인 프로필, 소속 그룹을 부여해주고 사내 정책에 따라 필요한 경우 MFA, Access-Key 등의 삭제 로직도 추가
          * IPA 계정 생성/수정/삭제 기능: freeIPA 라이브러리 적용
          * 관리가 미흡했던 사내 권한 그룹 정리 및 변경 적용
          * 계정 생성/삭제 요청시 Slack Bot 메시지 발송을 통한 관리자의 계정 생성 승인/반려 결정 및 결과 안내 기능 개발
          * 현재 계정 생성/삭제 기능은 담당자의 슬랙 메시지 승인시 자동 생성/삭제 되어 수립한 정책에 따라 신청자 혹은 계정 주인에게 DB이 발송되며, 비밀번호 초기화 기능은 담담자의 승인 없이 지원
          * 프로세스 간소화에 따른 계정 관리 부서 및 업무 요청자들의 불필요한 리소스를 줄여 사내 전반적인 업무 효율 개선<br/><br/>
      - layout: top-middle
        title: 사내 HR 프로그램 진행을 위한 전 직원 조 편성 백오피스 개발
        quote: >
          <b>Skill: Python, AWS Chalice, AWS Lambda, API Gateway, AuroraDB, Vue.js</b>
        description: |
          * 격주로 진행되는 사내 HR 프로그램 진행을 위한 직원 리스트 관리, 조 편성 및 결과 통보를 위한 백오피스 개발
          * 입사자/퇴사자 발생시 전체 리스트 수정 기능, 행사 진행시 불참자 반영 및 랜덤 조편성 알고리즘 추가
          * 전 직원이 쉽게 조회/검색 가능한 웹 페이지 개발
          * AWS Chalice 프레임워크 신규 적용을 통한 AWS Lambda, API Gateway 연동 및 배포<br/><br/>
      - layout: top-middle
        title: 이미지 Webp 변환 및 S3 업로드 기능 개발 - Google SEO 이미지 최적화
        quote: >
          <b>Skill: Python, Serverless Framework, AWS Lambda, SQS, S3, PIL</b>
        description: |
          * Google SEO 이미지 최적화를 위한 원본 이미지의 Webp 변환 및 S3 업로드 Api 개발
          * Serverless Framework를 통한 AWS Lambda handling
          * AWS SQS 메시지 큐 방식을 통한 이미지 전송 및 Lambda Trigger
          * 이미지 변환 라이브러리(PIL) 사용 (Webp 포맷으로 변환)
          * 이미지 상태에 따라 발생할 수 있는 다양한 에러(encoding 에러, 비정상적 이미지 에러, Webp 규격 초과 에러 등) handling -> 예상하지 못한 케이스에 대한 대응과 예외처리의 중요성을 깨달은 계기 <br/><br/>
      - layout: top-middle
        title: 사내 배포 시스템 개발
        quote: >
          <b>Skill: Go, GORM, gRPC, Protobuf, AuroraDB, Bitbucket-Pipeline, Vue.js</b>
        description: |
          * 사내 개발자들의 배포 진행 및 배포 히스토리 관리를 위한 “배포 시스템” 개발 프로젝트의 기획 / 개발 / 운영 단독 진행
          * Protobuf를 사용하여 내부 gRPC Gateway와 배포시스템 API와의 통신 구현
          * Atlassian REST APIs 공식 문서를 적극 활용하여, Bitbucket, Jira의 필요 기능 탑재
          * 배포 히스토리 CRUD API 및 사용자 편의를 고려한 원클릭 배포 실행/중지/재시작 기능 구현
          * 프로젝트별 파이프라인 리스트 조회 기능을 Bitbucket REST API에서 제공하지 않아 조회에 어려움이 있었음. 사용자가 선택한 repository, branch 정보에 따라 해당 bitbucket-pipelines.yml 파일의 파싱을 통해 파이프라인 리스트 정보 수집 후 사용자에게 제공
          * 개발팀마다 다르게 수립되어있던 배포 정책과 히스토리 관리 방식을 하나로 통일하기 위해 주도적으로 각 팀의 리드 대상 회의 주관 및 정책 수립 역할 수행
          * 현재 전 개발 부서가 배포 일정 등록, 배포 진행, 배포 히스토리 관리를 위해 사용 중<br/><br/>
      - layout: top-middle
        title: 셀러 전용 플랫폼 서비스 및 관리자 백오피스 개발
        quote: >
          <b>Skill: Python, Django Rest Framework, S3, AuroraDB, Vue.js</b>
        description: |
          * 사업팀의 셀러 관리 업무 자동화를 위한 총체적인 계약 관리 기능 신규 개발
          * RDB Schema 모델링, 셀러 계약 정보 CRUD API, 첨부 파일 S3 업로드 및 다운로드 기능 개발
          * 셀러 계약 히스토리 엑셀 다운로드 기능 개발
          * 셀러 상태/계약 히스토리에 따른 계약 종료/연장/재계약 등의 기능 구현
          * 수 년간 누적되어 있던 셀러 계약 히스토리 데이터를 온전하게 신규 개발 기능 DB에 마이그레이션 -> 기존 관리 엑셀파일 파싱 및 스크립트 작성
          * 엑셀파일로 관리하던 사업 부서의 셀러 계약 관리 업무 방식을 백오피스 기능 중심으로 전환함에 따라 업무 편의 및 효율성 증대 <br/><br/>
      - layout: top-middle
        title: 사기 의심 채팅 모니터링 기능 고도화
        quote: >
          <b>Skill: Python, Flask, SQLAlchemy, AuroraDB, MongoDB, Vue.js</b>
        description: |
          * 사기의심채팅 모니터링 목적의 채팅 화면 개발 및 RESTful API 개발
          * 사기의심 여부 반복 체크를 위한 프로세스 개발 및 도입
          * 사기의심채팅 리스트 엑셀 다운로드 기능 및 엑셀 다운로드 공통 모듈 개발
          * 사기의심 유저의 동일 디바이스 uuid 검출 여부 조회 기능 개발
          * FDS 조회 결과에 따른 자동 제재 프로세스 개발
          * 채팅 내용 조회를 위한 모니터링 전용 채팅 화면 및 채팅화면에 사기여부 체크/수신자,발신자 정보 조회 기능 개발
          * 사기 의심 채팅 적발에 따른 즉각적인 회원 제재 및 반복 검토를 통한 적중률 증가에 기여<br/><br/>

  - title: Education
    layout: list
    content:
      - layout: left
        title: 경희대학교 (Kyunghee University)
        caption: 2009.03 - 2015.02
        sub_title: Bachelor of Science, Medical Science
        description: |
          * 생명과학, 화학 관련 주요 전공 과목 이수
          * 해부학, 약리학 등의 기초의학 관련 주요 전공 과목 이수
          * 유전자 재조합, 형질전환 등과 같은 다양한 주제의 in vivo, in vitro 실험교육을 통한 연구능력 배양 훈련

  - title: Aspirations as a Developer
    layout: text
    content: |
      - **"Growth itself contains the germ of happiness"**<br>
        제가 인생의 좌표로 삼고 있는 명언입니다. 이와 같이 인생의 가장 중요한 가치는 ‘**성장**‘이라고 생각합니다. 회사와 개인의 지속적인 동반성장을 도모하는 개발자가 되고자 합니다.
        그리하여 산전수전 전부 경험한 개발자가 되어, 그 어떤 예상치 못한 이슈에도 흔들리지 않고 대처할 수 있는 개발자가 되고자 합니다. 
        또한 이러한 안정성을 바탕으로 **동료들을 이끄는 기술조직의 리더가 되는 것**이 목표 입니다.

#      Look at this cool image
#      ![Trees](/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
